server:
  port: 8085

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/auth-database

  redis:
    host: redis
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true