server:
  port: 8085

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/auth-database

  redis:
    host: redis
    port: 6379